version: '3.4'

x-frontend-base: &frontend-base
    image: node:alpine
    volumes:
        - ./journali-frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    entrypoint: yarn

x-api-base: &api-base
    image: rust:latest
    volumes:
        - ./journali-api:/usr/src/api
        - ./.cache/cargo:/usr/local/cargo-cache
    environment:
        - CARGO_HOME=/usr/local/cargo-cache
    working_dir: /usr/src/api
    entrypoint: cargo

services:
    cargo:
        <<: *api-base
    yarn:
        <<: *frontend-base
    install:
        <<: *frontend-base
        command: install
    build-dev:
        <<: *frontend-base
        command: build:dev
    build-prod:
        <<: *frontend-base
        command: build:prod
