version: '3.4'

x-frontend-base: &frontend-base
    image: node:alpine
    volumes:
        - ./journali-frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    entrypoint: yarn

x-api-base: &api-base
    image: rust:latest
    volumes:
        - ./journali-api:/usr/src/api
        - ./.cache/cargo:/usr/local/cargo/registry
    working_dir: /usr/src/api
    entrypoint: cargo
    networks:
        - journali

services:
    cargo:
        <<: *api-base
    yarn:
        <<: *frontend-base
    install:
        <<: *frontend-base
        command: install
    build-dev:
        <<: *frontend-base
        command: build:dev
    build-prod:
        <<: *frontend-base
        command: build:prod
    diesel:
        <<: *api-base
        image: christophwurst/diesel-cli
        entrypoint: diesel
        env_file: dev.env
    migrate:
        <<: *api-base
        image: christophwurst/diesel-cli
        entrypoint: diesel
        command: migration run
        env_file: dev.env

networks:
    journali:
        external: true
