version: '3'

services:
    frontend:
        image: node:latest
        volumes:
            - ./journali-frontend:/usr/src/frontend
        working_dir: /usr/src/frontend
        command: yarn serve:dev
        ports:
            - 8080:8080
    api:
        image: rust:latest
        volumes:
            - ./journali-api:/usr/src/api
            - ./.cache/cargo:/usr/local/cargo-cache
        environment:
            - CARGO_HOME=/usr/local/cargo-cache
        working_dir: /usr/src/api
        entrypoint: cargo
        command: run server
        expose:
            - 8000
    db:
        image: postgres:latest
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file: ./dev.env
        expose:
            - 5432

volumes:
    db-data:
